# Generated by Django 5.0.3 on 2024-07-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
